# Configuration for SeeMore.

# Please don't change this!
version: 3

# The delay (in ticks) before a player's view distance is lowered after their client settings change.
#  * This stops players overloading the server by constantly changing their view distance.
update-delay: 600

# Whether the plugin should log to the console when it changes a player's view distance.
log-changes: true

# These settings can be specified per world.
#  * Note: If a world is not listed here or if a setting is missing, it will use the settings listed under the default
#    section.
world-settings:
  default:
    # The maximum view distance a player in this world can have.
    # Set to -1 to use the server's configured view distance for this world.
    maximum-view-distance: -1

# Settings for specific integrations. Only works with the corresponding plugin installed.
integration-settings:
  essentials:
    # View distance that will be set for a player when they go AFK.
    # The AFK view distance will only be applied if the player's
    # view distance is higher than this value when they go AFK.
    # Note: Set to -1 to disable this feature.
    afk-view-distance: 4
    
